apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pacman-rancher.fullname" . }}
  labels:
    {{- include "pacman-rancher.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pacman-rancher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pacman-rancher.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pacman-rancher.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http-server
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http-server
          readinessProbe:
            httpGet:
              path: /
              port: http-server
          env:
          - name: MONGO_SERVICE_HOST
            value: mongo
          - name: MONGO_AUTH_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: {{ .Release.Name }}-mongo-auth
          - name: MONGO_AUTH_PWD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: {{ .Release.Name }}-mongo-auth
          - name: MONGO_DATABASE
            value: pacman
          - name: MY_MONGO_PORT
            value: "27017"
          - name: MONGO_USE_SSL
            value: "false"
          - name: MONGO_VALIDATE_SSL
            value: "false"
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
