apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.mongo.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        name: mongo
    spec:
      # initContainers:
      # - args:
      #   - |
      #     mkdir -p /bitnami/mongodb
      #     chown -R "1001:1001" "/bitnami/mongodb"
      #   command:
      #   - /bin/bash
      #   - -ec
      #   image: docker.io/bitnami/bitnami-shell:10-debian-10-r158
      #   imagePullPolicy: Always
      #   name: volume-permissions
      #   resources: {}
      #   securityContext:
      #     runAsUser: 0
      #   terminationMessagePath: /dev/termination-log
      #   terminationMessagePolicy: File
      #   volumeMounts:
      #   - mountPath: /bitnami/mongodb
      #     name: mongo-db
      # restartPolicy: Always
      # schedulerName: default-scheduler
      # securityContext:
      #   fsGroup: 1001
      # serviceAccountName: default
      # terminationGracePeriodSeconds: 30
      volumes:
      - name: mongo-db
        persistentVolumeClaim:
          claimName: mongo-storage
      - name: pacman-mongo-common-scripts-volume
        configMap:
          defaultMode: 0755
          name: pacman-mongo-common-scripts
      securityContext: 
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag | default .Chart.AppVersion }}"
        env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-admin-password
              name: {{ .Release.Name }}-mongo-auth
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Release.Name }}-mongo-auth
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Release.Name }}-mongo-auth
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Release.Name }}-mongo-auth
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DISABLE_JAVASCRIPT
          value: "no"
        - name: MONGODB_ENABLE_JOURNAL
          value: "yes"
        - name: MONGODB_PORT_NUMBER
          value: "27017"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        ports:
          - name: mongo
            containerPort: 27017
        volumeMounts:
        - name: mongo-db
          subPath: mongodb
          mountPath: /bitnami/mongodb/
        - name: pacman-mongo-common-scripts-volume
          mountPath: /bitnami/common-scripts/
        readinessProbe:
          exec:
            command:
              - /bitnami/common-scripts/readiness-probe.sh
          initialDelaySeconds: 5
          periodSeconds: 20
        livenessProbe:
          exec:
            command:
              - /bitnami/common-scripts/ping-mongodb.sh
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          exec:
            command:
              - /bitnami/common-scripts/startup-probe.sh
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 10
