name: "Code Scanning"

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
  watch:
    types: [started]

env:
  REGISTRY: ghcr.io/austriandatalab
  IMAGE_NAME: pacman

jobs:
  Trivy-Scan:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
