name: Run integration test using docker-compose
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - name: Build the localdev environment
        run: docker-compose -f docker-compose.test-integration.yml up -d 
      - name: Setup
        run: sudo rm -rf ./mongodb && mkdir ./mongodb && sudo chown -R 1001:1001 ./mongodb
      - name: Test 
        run: docker exec pacman-app-integration /bin/bash -c "npm run test-integration" 
